"""
Constants, Master Vocabularies, UOM Standards, Fraction Conversions, 
and Delivery Schema Definitions for the Unilog Product Intelligence Pipeline.
"""

# Master 252-column delivery schema strictly in order matching the ground truth specification
DELIVERY_COLUMNS_252 = [
    'MFR URL',
    'Ref URL 1',
    'Ref URL 2',
    'Ref URL 3',
    'Ref URL 4',
    'Ref URL 5',
    'PART_NUMBER',
    'Dept',
    'Class',
    'Fine',
    'SKU - MY_PART_NUMBER',
    'Mfg_Part_Num',
    'Part_Desc',
    'E1_Brand',
    'Unilog_Brand',
    'DIB_Brand',
    'Part_Manuf',
    'MANUFACTURER_NAME',
    'BRAND_NAME',
    'TRADE_NAME',
    'MANUFACTURER_PART_NUMBER',
    'ALTERNATE_PART_NUMBER',
    'Classpath',
    'MOBILE_DESC',
    'INVOICE_DESC',
    'SHORT_DESC',
    'LONG_DESC1',
    'RETAIL_DESC',
    'MARKETING_DESCRIPTION',
    'ITEM_FEATURES_1',
    'ITEM_FEATURES_2',
    'ITEM_FEATURES_3',
    'ITEM_FEATURES_4',
    'ITEM_FEATURES_5',
    'ITEM_FEATURES_6',
    'ITEM_FEATURES_7',
    'ITEM_FEATURES_8',
    'ITEM_FEATURES_9',
    'ITEM_FEATURES_10',
    'ITEM_FEATURES_11',
    'ITEM_FEATURES_12',
    'ITEM_FEATURES_13',
    'ITEM_FEATURES_14',
    'ITEM_FEATURES_15',
    'ITEM_FEATURES_16',
    'ITEM_FEATURES_17',
    'ITEM_FEATURES_18',
    'ITEM_FEATURES_19',
    'ITEM_FEATURES_20',
    'With',
    'Standard/Approvals',
    'Prop 65',
    'Application',
    'Includes',
    'Product Name',
]

# Append 50 attribute triplets: ATTRIBUTE_LABEL i, ATTRIBUTE_VALUE i, ATTRIBUTE_UOM i (i=1..50)
for i in range(1, 51):
    DELIVERY_COLUMNS_252.append(f'ATTRIBUTE_LABEL {i}')
    DELIVERY_COLUMNS_252.append(f'ATTRIBUTE_VALUE {i}')
    DELIVERY_COLUMNS_252.append(f'ATTRIBUTE_UOM {i}')

# Append remaining 47 metadata, dimension, digital asset, and compliance fields (total: 55 + 150 + 47 = 252)
REMAINING_DELIVERY_COLUMNS = [
    'UPC',
    'EAN',
    'GTIN',
    'UNSPSC',
    'Warranty',
    'List Price',
    'Selling Qty',
    'Selling UOM',
    'Standard Packaging Information',
    'LENGTH',
    'LENGTH_UOM',
    'HEIGHT',
    'HEIGHT_UOM',
    'WIDTH',
    'WIDTH_UOM',
    'WEIGHT',
    'WEIGHT_UOM',
    'VOLUME',
    'VOLUME_UOM',
    'Product Image',
    'Alternate Image 1',
    'Alternate Image 2',
    'Alternate Image 3',
    'Alternate Image 4',
    'SDS',
    'SDS_1',
    'Warranty Information',
    'Catalog',
    'Specification Sheet',
    'Instruction/Installation Manual',
    'Service Manual',
    'Owners/User Manual',
    'Line Drawing',
    'MTR',
    'RoHS',
    'Full Engineering Drawing',
    'Energy Star Guide',
    'Technical Bulletin',
    'Submittal',
    'Compatibility Chart',
    'Size Chart',
    'Product Label/Insert',
    'Video Link',
    'Video Link 1',
    'Country Of Origin',
    'Discontinued',
    'Actual Image (Yes/No)'
]
DELIVERY_COLUMNS_252.extend(REMAINING_DELIVERY_COLUMNS)

assert len(DELIVERY_COLUMNS_252) == 252, f"Delivery columns count must be 252, got {len(DELIVERY_COLUMNS_252)}"


# 63 Exact Inch Conversions from Decimal_Fraction.xlsx (1/64 to 63/64)
DECIMAL_TO_FRACTION_MAP = {
    0.015625: "1/64",
    0.03125:  "1/32",
    0.046875: "3/64",
    0.0625:   "1/16",
    0.078125: "5/64",
    0.09375:  "3/32",
    0.109375: "7/64",
    0.125:    "1/8",
    0.140625: "9/64",
    0.15625:  "5/32",
    0.171875: "11/64",
    0.1875:   "3/16",
    0.203125: "13/64",
    0.21875:  "7/32",
    0.234375: "15/64",
    0.25:     "1/4",
    0.265625: "17/64",
    0.28125:  "9/32",
    0.296875: "19/64",
    0.3125:   "5/16",
    0.328125: "21/64",
    0.34375:  "11/32",
    0.359375: "23/64",
    0.375:    "3/8",
    0.390625: "25/64",
    0.40625:  "13/32",
    0.421875: "27/64",
    0.4375:   "7/16",
    0.453125: "29/64",
    0.46875:  "15/32",
    0.484375: "31/64",
    0.5:      "1/2",
    0.515625: "33/64",
    0.53125:  "17/32",
    0.546875: "35/64",
    0.5625:   "9/16",
    0.578125: "37/64",
    0.59375:  "19/32",
    0.609375: "39/64",
    0.625:    "5/8",
    0.640625: "41/64",
    0.65625:  "21/32",
    0.671875: "43/64",
    0.6875:   "11/16",
    0.703125: "45/64",
    0.71875:  "23/32",
    0.734375: "47/64",
    0.75:     "3/4",
    0.765625: "49/64",
    0.78125:  "25/32",
    0.796875: "51/64",
    0.8125:   "13/16",
    0.828125: "53/64",
    0.84375:  "27/32",
    0.859375: "55/64",
    0.875:    "7/8",
    0.890625: "57/64",
    0.90625:  "29/32",
    0.921875: "59/64",
    0.9375:   "15/16",
    0.953125: "61/64",
    0.96875:  "31/32",
    0.984375: "63/64"
}


# Master UOM Standards & Abbreviations (Unilog House-Style)
# Mapping messy variations -> single approved standard abbreviation
UOM_STANDARDIZATION_MAP = {
    # Length / Dimensions
    "inch": "in",
    "inches": "in",
    "in.": "in",
    "in": "in",
    "\"": "in",
    "''": "in",
    "foot": "ft",
    "feet": "ft",
    "ft.": "ft",
    "ft": "ft",
    "'": "ft",
    "millimeter": "mm",
    "millimeters": "mm",
    "mm.": "mm",
    "mm": "mm",
    "centimeter": "cm",
    "centimeters": "cm",
    "cm.": "cm",
    "cm": "cm",
    "meter": "m",
    "meters": "m",
    "m.": "m",
    "m": "m",
    "yard": "yd",
    "yards": "yd",
    "yd": "yd",

    # Electrical
    "volt": "V",
    "volts": "V",
    "v": "V",
    "v.": "V",
    "vac": "VAC",
    "vdc": "VDC",
    "amp": "A",
    "amps": "A",
    "ampere": "A",
    "amperes": "A",
    "a": "A",
    "a.": "A",
    "milliamp": "mA",
    "milliamps": "mA",
    "ma": "mA",
    "watt": "W",
    "watts": "W",
    "w": "W",
    "kilowatt": "kW",
    "kilowatts": "kW",
    "kw": "kW",
    "kw-hr": "kW-hr",
    "kwh": "kW-hr",
    "hertz": "Hz",
    "hz": "Hz",

    # Acoustic / Sound
    "dba": "dBA",
    "db": "dBA",
    "decibel": "dBA",
    "decibels": "dBA",

    # Pressure
    "psi": "psi",
    "psig": "psig",
    "bar": "bar",
    "kpa": "kPa",
    "mpa": "MPa",
    "#": "lb",

    # Flow / Speed / Mechanics
    "gpm": "gpm",
    "cfm": "cfm",
    "rpm": "rpm",
    "mph": "mph",
    "fpm": "fpm",
    "hp": "hp",
    "horsepower": "hp",

    # Weight / Mass
    "pound": "lb",
    "pounds": "lb",
    "lbs": "lb",
    "lb.": "lb",
    "lb": "lb",
    "ounce": "oz",
    "ounces": "oz",
    "oz.": "oz",
    "oz": "oz",
    "kilogram": "kg",
    "kilograms": "kg",
    "kg.": "kg",
    "kg": "kg",
    "gram": "g",
    "grams": "g",
    "g.": "g",
    "g": "g",

    # Temperature
    "deg f": "deg F",
    "deg. f": "deg F",
    "degree f": "deg F",
    "fahrenheit": "deg F",
    "deg c": "deg C",
    "deg. c": "deg C",
    "celsius": "deg C",

    # Volume / Capacity
    "gallon": "gal",
    "gallons": "gal",
    "gal.": "gal",
    "gal": "gal",
    "quart": "qt",
    "quarts": "qt",
    "qt.": "qt",
    "qt": "qt",
    "pint": "pt",
    "pints": "pt",
    "pt.": "pt",
    "pt": "pt",
    "fluid ounce": "fl-oz",
    "fl oz": "fl-oz",
    "fl-oz": "fl-oz",
    "liter": "L",
    "liters": "L",
    "l": "L",
    "milliliter": "mL",
    "milliliters": "mL",
    "ml": "mL",

    # Packaging / Counts
    "piece": "ea",
    "each": "ea",
    "ea": "ea",
    "pack": "pk",
    "pk": "pk",
    "box": "bx",
    "bx": "bx",
    "pair": "pr",
    "pr": "pr",
    "set": "set",
    "roll": "roll",
    "case": "cs",
    "cs": "cs"
}


# Canonical Manufacturer and Brand Knowledge Base (UniCat master registry)
CANONICAL_MANUFACTURERS_AND_BRANDS = {
    # Appliances & HVAC
    "frigidaire": {
        "mfr_name": "Rheem Manufacturing",
        "brand_name": "FRIGIDAIRE®",
        "mfr_code": "RHEEM",
        "brand_code": "FRIG",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "mfr_url_base": "https://www.frigidaire.com/en/p/owner-center/product-support/",
    },
    "whirlpool": {
        "mfr_name": "Whirlpool Corporation",
        "brand_name": "Whirlpool®",
        "mfr_code": "WHIRL",
        "brand_code": "WHIR",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "mfr_url_base": "https://learnwhirlpool.com/smartsearchresults?searchtext=",
    },
    "appliance dealers cooperative": {
        "mfr_name": "Rheem Manufacturing",
        "brand_name": "FRIGIDAIRE®",
        "mfr_code": "RHEEM",
        "brand_code": "FRIG",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "mfr_url_base": "https://www.frigidaire.com/en/p/owner-center/product-support/",
    },
    "ge appliances": {
        "mfr_name": "GE Appliances, a Haier company",
        "brand_name": "GE®",
        "mfr_code": "GEAPP",
        "brand_code": "GE",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "mfr_url_base": "https://www.geappliances.com/p/",
    },
    "bosch": {
        "mfr_name": "BSH Home Appliances Corporation",
        "brand_name": "Bosch®",
        "mfr_code": "BSH",
        "brand_code": "BOSCH",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "mfr_url_base": "https://www.bosch-home.com/us/products/",
    },

    # Abrasives & Cutting Tools
    "freud": {
        "mfr_name": "Freud America, Inc.",
        "brand_name": "Diablo®",
        "mfr_code": "FREUD",
        "brand_code": "DIAB",
        "dept": "Power Tools & Accessories",
        "class": "Cutting Tools & Saw Blades",
        "fine": "Abrasives & Blades",
        "classpath": "Power Tools & Accessories>Cutting Tools>Saw Blades & Abrasive Wheels",
        "mfr_url_base": "https://www.diablotools.com/products/",
    },
    "diablo": {
        "mfr_name": "Freud America, Inc.",
        "brand_name": "Diablo®",
        "mfr_code": "FREUD",
        "brand_code": "DIAB",
        "dept": "Power Tools & Accessories",
        "class": "Cutting Tools & Saw Blades",
        "fine": "Abrasives & Blades",
        "classpath": "Power Tools & Accessories>Cutting Tools>Saw Blades & Abrasive Wheels",
        "mfr_url_base": "https://www.diablotools.com/products/",
    },
    "3m": {
        "mfr_name": "3M Company",
        "brand_name": "3M™",
        "mfr_code": "3MCO",
        "brand_code": "3M",
        "dept": "Abrasives",
        "class": "Sanding & Finishing",
        "fine": "Abrasive Discs & Belts",
        "classpath": "Abrasives & Surface Preparation>Sanding Discs & Film Discs>Hook & Loop Discs",
        "mfr_url_base": "https://www.3m.com/3M/en_US/p/d/",
    },
    "jam industrial supply": {
        "mfr_name": "3M Company",
        "brand_name": "3M™",
        "mfr_code": "3MCO",
        "brand_code": "3M",
        "dept": "Abrasives",
        "class": "Sanding & Finishing",
        "fine": "Abrasive Discs & Belts",
        "classpath": "Abrasives & Surface Preparation>Sanding Discs & Film Discs>Hook & Loop Discs",
        "mfr_url_base": "https://www.3m.com/3M/en_US/p/d/",
    },
    "mirka": {
        "mfr_name": "Mirka Ltd.",
        "brand_name": "Mirka®",
        "mfr_code": "MIRKA",
        "brand_code": "MIRK",
        "dept": "Abrasives",
        "class": "Sanding & Finishing",
        "fine": "Net Abrasives & Sheets",
        "classpath": "Abrasives & Surface Preparation>Abranet Abrasive Sheets & Strips",
        "mfr_url_base": "https://www.mirka.com/en-us/products/",
    },

    # Power Tools & Systems
    "milwaukee": {
        "mfr_name": "Milwaukee Electric Tool Corporation",
        "brand_name": "Milwaukee®",
        "mfr_code": "MILW",
        "brand_code": "MILW",
        "dept": "Power Tools & Equipment",
        "class": "Cordless & Corded Tools",
        "fine": "Power Tool Accessories",
        "classpath": "Power Tools & Equipment>Power Tool Accessories>Bits & Fastening",
        "mfr_url_base": "https://www.milwaukeetool.com/Products/",
    },
    "dewalt": {
        "mfr_name": "Stanley Black & Decker, Inc.",
        "brand_name": "DEWALT®",
        "mfr_code": "SWK",
        "brand_code": "DEW",
        "dept": "Power Tools & Equipment",
        "class": "Cordless & Corded Tools",
        "fine": "Power Tool Accessories",
        "classpath": "Power Tools & Equipment>Power Tool Accessories>Cutting & Drilling",
        "mfr_url_base": "https://www.dewalt.com/products/",
    },
    "black & decker": {
        "mfr_name": "Stanley Black & Decker, Inc.",
        "brand_name": "DEWALT®",
        "mfr_code": "SWK",
        "brand_code": "DEW",
        "dept": "Power Tools & Equipment",
        "class": "Cordless & Corded Tools",
        "fine": "Power Tool Accessories",
        "classpath": "Power Tools & Equipment>Power Tool Accessories>Cutting & Drilling",
        "mfr_url_base": "https://www.dewalt.com/products/",
    },
    "makita": {
        "mfr_name": "Makita U.S.A., Inc.",
        "brand_name": "Makita®",
        "mfr_code": "MAK",
        "brand_code": "MAK",
        "dept": "Power Tools & Equipment",
        "class": "Cordless & Corded Tools",
        "fine": "Power Tool Accessories",
        "classpath": "Power Tools & Equipment>Power Tools>Drills & Fasteners",
        "mfr_url_base": "https://www.makitatools.com/products/details/",
    },
    "festool": {
        "mfr_name": "Festool USA",
        "brand_name": "Festool®",
        "mfr_code": "FESTO",
        "brand_code": "FEST",
        "dept": "Power Tools & Equipment",
        "class": "Precision Woodworking",
        "fine": "Track Saws & Routers",
        "classpath": "Power Tools & Equipment>Precision Power Tools>Joiners & Sanders",
        "mfr_url_base": "https://www.festoolusa.com/products/",
    },

    # Lighting & Electrical
    "phillips lighting": {
        "mfr_name": "Signify North America Corporation",
        "brand_name": "Philips®",
        "mfr_code": "SIGN",
        "brand_code": "PHIL",
        "dept": "Lighting & Electrical",
        "class": "Lamps & Bulbs",
        "fine": "LED & Fluorescent Lamps",
        "classpath": "Lighting & Electrical>Lamps, Bulbs & Ballasts>LED Lamps",
        "mfr_url_base": "https://www.lighting.philips.com/main/prof/lamps/",
    },
    "philips": {
        "mfr_name": "Signify North America Corporation",
        "brand_name": "Philips®",
        "mfr_code": "SIGN",
        "brand_code": "PHIL",
        "dept": "Lighting & Electrical",
        "class": "Lamps & Bulbs",
        "fine": "LED & Fluorescent Lamps",
        "classpath": "Lighting & Electrical>Lamps, Bulbs & Ballasts>LED Lamps",
        "mfr_url_base": "https://www.lighting.philips.com/main/prof/lamps/",
    },
    "kichler": {
        "mfr_name": "Kichler Lighting LLC",
        "brand_name": "Kichler®",
        "mfr_code": "KICH",
        "brand_code": "KICH",
        "dept": "Lighting & Electrical",
        "class": "Fixtures & Luminaires",
        "fine": "Indoor & Outdoor Lighting",
        "classpath": "Lighting & Electrical>Commercial & Residential Lighting>Decorative Fixtures",
        "mfr_url_base": "https://www.kichler.com/products/",
    },
    "satco": {
        "mfr_name": "Satco Products, Inc.",
        "brand_name": "SATCO®",
        "mfr_code": "SATCO",
        "brand_code": "SATC",
        "dept": "Lighting & Electrical",
        "class": "Lamps & Bulbs",
        "fine": "LED Bulbs & Fixtures",
        "classpath": "Lighting & Electrical>Lamps, Bulbs & Ballasts>LED Lamps",
        "mfr_url_base": "https://www.satco.com/products/",
    },
    "leviton": {
        "mfr_name": "Leviton Manufacturing Co., Inc.",
        "brand_name": "Leviton®",
        "mfr_code": "LEVI",
        "brand_code": "LEVI",
        "dept": "Electrical Distribution",
        "class": "Wiring Devices",
        "fine": "Switches & Receptacles",
        "classpath": "Lighting & Electrical>Wiring Devices & Receptacles>GFCI Receptacles",
        "mfr_url_base": "https://www.leviton.com/en/products/",
    },
    "southwire": {
        "mfr_name": "Southwire Company, LLC",
        "brand_name": "Southwire®",
        "mfr_code": "SOUT",
        "brand_code": "SOUT",
        "dept": "Electrical Distribution",
        "class": "Wire & Cable",
        "fine": "Building Wire & Conduit",
        "classpath": "Lighting & Electrical>Wire & Cable>Commercial Building Wire",
        "mfr_url_base": "https://www.southwire.com/wire-cable/",
    },

    # Building Materials, Decking & Millwork
    "trex": {
        "mfr_name": "Trex Company, Inc.",
        "brand_name": "Trex®",
        "mfr_code": "TREX",
        "brand_code": "TREX",
        "dept": "Building Materials",
        "class": "Decking & Railing",
        "fine": "Composite Decking Boards",
        "classpath": "Building Materials>Decking & Railing>Composite Deck Boards",
        "mfr_url_base": "https://www.trex.com/products/",
    },
    "timbertech": {
        "mfr_name": "The AZEK Company Inc.",
        "brand_name": "TimberTech®",
        "mfr_code": "AZEK",
        "brand_code": "TIMB",
        "dept": "Building Materials",
        "class": "Decking & Railing",
        "fine": "Capped Composite Decking",
        "classpath": "Building Materials>Decking & Railing>Capped Composite Deck Boards",
        "mfr_url_base": "https://www.timbertech.com/products/",
    },
    "boise cascade": {
        "mfr_name": "Boise Cascade Company",
        "brand_name": "Boise Cascade®",
        "mfr_code": "BOICA",
        "brand_code": "BOIS",
        "dept": "Building Materials",
        "class": "Engineered Wood Products",
        "fine": "Beams & I-Joists",
        "classpath": "Building Materials>Lumber & Composites>Engineered Wood Products",
        "mfr_url_base": "https://www.bc.com/products/",
    },
    "parksite": {
        "mfr_name": "Parksite Inc.",
        "brand_name": "DuPont™ Corian®",
        "mfr_code": "PARK",
        "brand_code": "CORI",
        "dept": "Building Materials",
        "class": "Surfaces & Cladding",
        "fine": "Solid Surfaces & Siding",
        "classpath": "Building Materials>Siding & Cladding>Architectural Wall Panels",
        "mfr_url_base": "https://www.parksite.com/products/",
    },
    "u s lumber": {
        "mfr_name": "U.S. Lumber Group, LLC",
        "brand_name": "U.S. Lumber®",
        "mfr_code": "USLUM",
        "brand_code": "USLU",
        "dept": "Building Materials",
        "class": "Specialty Millwork & Trim",
        "fine": "Composite Trim & Moulding",
        "classpath": "Building Materials>Millwork & Moulding>Exterior Trim Boards",
        "mfr_url_base": "https://www.uslumber.com/products/",
    },

    # Plumbing, Faucets & Pipe Fittings
    "moen": {
        "mfr_name": "Moen Incorporated",
        "brand_name": "Moen®",
        "mfr_code": "MOEN",
        "brand_code": "MOEN",
        "dept": "Plumbing",
        "class": "Faucets & Fixtures",
        "fine": "Kitchen & Bath Sink Faucets",
        "classpath": "Plumbing>Faucets & Fixtures>Kitchen & Bath Sink Faucets",
        "mfr_url_base": "https://www.moen.com/products/",
    },
    "kohler": {
        "mfr_name": "Kohler Co.",
        "brand_name": "Kohler®",
        "mfr_code": "KOHL",
        "brand_code": "KOHL",
        "dept": "Plumbing",
        "class": "Faucets & Fixtures",
        "fine": "Kitchen & Bath Sink Faucets",
        "classpath": "Plumbing>Faucets & Fixtures>Kitchen & Bath Sink Faucets",
        "mfr_url_base": "https://www.us.kohler.com/us/browse/faucets/",
    },
    "nibco": {
        "mfr_name": "NIBCO INC.",
        "brand_name": "NIBCO®",
        "mfr_code": "NIBC",
        "brand_code": "NIBC",
        "dept": "Plumbing",
        "class": "Pipes, Valves & Fittings",
        "fine": "Pipe Fittings & Couplings",
        "classpath": "Plumbing>Pipes, Valves & Fittings>Pipe Fittings>Couplings",
        "mfr_url_base": "https://www.nibco.com/products/",
    },
    "viega": {
        "mfr_name": "Viega LLC",
        "brand_name": "Viega®",
        "mfr_code": "VIEG",
        "brand_code": "VIEG",
        "dept": "Plumbing",
        "class": "Pipes, Valves & Fittings",
        "fine": "Press Fittings & Valves",
        "classpath": "Plumbing>Pipes, Valves & Fittings>Press Fittings>ProPress",
        "mfr_url_base": "https://www.viega.us/en/products/",
    },
}

# Controlled Vocabulary LOVs for Categories
CATEGORY_LOV_SPECS = {
    "dishwashers": {
        "product_name": "Dishwasher",
        "dept": "Appliances",
        "class": "Large Appliances",
        "fine": "Dishwashers",
        "classpath": "Appliances & Consumer Electronics>Kitchen Appliances>Built-In Dishwashers",
        "attribute_sequence": [
            ("Series", None),
            ("Model", None),
            ("Number of Wash Cycles", None),
            ("Voltage Rating", "V"),
            ("Amperage Rating", "A"),
            ("Mounting Type", None),
            ("Plug Type", None),
            ("Size", None),
            ("Depth With Door Open", "in"),
            ("Minimum Height", "in"),
            ("Maximum Height", "in"),
            ("Sound Level", "dBA"),
            ("Material", None),
            ("Color", None),
            ("Additional Information", None),
        ]
    },
    "fittings": {
        "product_name": "Fitting",
        "dept": "Plumbing",
        "class": "Pipes, Valves & Fittings",
        "fine": "Pipe Fittings",
        "classpath": "Plumbing>Pipes, Valves & Fittings>Pipe Fittings>Couplings",
        "attribute_sequence": [
            ("Fitting Type", None),
            ("Nominal Size", "in"),
            ("Connection Type", None),
            ("Material", None),
            ("Pressure Rating", "psi"),
            ("Temperature Rating", "deg F"),
            ("Schedule/Class", None),
            ("Standard/Approvals", None),
            ("Additional Information", None),
        ]
    },
    "faucets": {
        "product_name": "Faucet",
        "dept": "Plumbing",
        "class": "Faucets & Fixtures",
        "fine": "Kitchen & Bath Sink Faucets",
        "classpath": "Plumbing>Faucets & Fixtures>Kitchen & Bath Sink Faucets",
        "attribute_sequence": [
            ("Faucet Type", None),
            ("Flow Rate", "gpm"),
            ("Number of Handles", None),
            ("Mounting Type", None),
            ("Spout Reach", "in"),
            ("Spout Height", "in"),
            ("Finish/Color", None),
            ("Material", None),
            ("Valve Type", None),
            ("Standard/Approvals", None),
            ("Additional Information", None),
        ]
    },
    "abrasives": {
        "product_name": "Sanding Disc",
        "dept": "Abrasives",
        "class": "Sanding & Finishing",
        "fine": "Abrasive Discs & Belts",
        "classpath": "Abrasives & Surface Preparation>Sanding Discs & Film Discs>Hook & Loop Discs",
        "attribute_sequence": [
            ("Diameter", "in"),
            ("Grit", "Grit"),
            ("Abrasive Material", None),
            ("Backing Material", None),
            ("Attachment Type", None),
            ("Hole Pattern", None),
            ("Color", None),
            ("Package Quantity", "pk"),
            ("Series", None),
            ("Additional Information", None),
        ]
    },
    "lamps": {
        "product_name": "LED Lamp",
        "dept": "Lighting & Electrical",
        "class": "Lamps & Bulbs",
        "fine": "LED Lamps",
        "classpath": "Lighting & Electrical>Lamps, Bulbs & Ballasts>LED Lamps",
        "attribute_sequence": [
            ("Wattage", "W"),
            ("Voltage Rating", "V"),
            ("Lumens", "lm"),
            ("Color Temperature", "K"),
            ("Base Type", None),
            ("Bulb Shape", None),
            ("Dimmable", None),
            ("Average Life", "hr"),
            ("Color Rendering Index (CRI)", None),
            ("Additional Information", None),
        ]
    },
    "power_tools": {
        "product_name": "Saw Blade",
        "dept": "Power Tools & Accessories",
        "class": "Cutting Tools & Saw Blades",
        "fine": "Saw Blades",
        "classpath": "Power Tools & Accessories>Cutting Tools>Saw Blades & Abrasive Wheels",
        "attribute_sequence": [
            ("Diameter", "in"),
            ("Teeth Count", "T"),
            ("Arbor Size", "in"),
            ("Kerf", "in"),
            ("Material Cut", None),
            ("Hook Angle", "deg"),
            ("Tooth Grind", None),
            ("Series", None),
            ("Additional Information", None),
        ]
    },
    "decking": {
        "product_name": "Decking Board",
        "dept": "Building Materials",
        "class": "Decking & Railing",
        "fine": "Composite Deck Boards",
        "classpath": "Building Materials>Decking & Railing>Composite Deck Boards",
        "attribute_sequence": [
            ("Length", "ft"),
            ("Width", "in"),
            ("Thickness", "in"),
            ("Color/Finish", None),
            ("Profile Type", None),
            ("Material", None),
            ("Series", None),
            ("Warranty", None),
            ("Additional Information", None),
        ]
    }
}
